### ISSUE TITLE
[Feature request] Save video timestamp

### ISSUE THREAD

**Issue by stelioskat** [11Tuvork28/invidious#1]
It would be great to save the video timestamp. This way it is much easier to watch longer videos in more sessions, without having to search where it was paused.

This feature is already implemented in yewtu.be . However, the german host invidio.xamh.de, that I use which uses this source, doesn't have it yet. It would be greatly appreciated, if you could merge this feature too. Thanks!

**Comment by AndromedaCLI** [comment]
Hi, I merged the changes. Thanks for bringing this up 👍
