### ISSUE TITLE
[Feature request] Hide videos shorter than X seconds

### ISSUE THREAD

**Issue by rex4539** [11Tuvork28/invidious#14]
**Is your feature request related to a problem? Please describe.**

This is an attempt to solve the ultra annoying short videos issue.

**Describe the solution you'd like**

Add an option in Preferences "Hide videos shorter than" where user can enter any number in seconds, so any videos shorter than this number will be hidden from the UI.

**Comment by AndromedaCLI** [comment]
Will look into it but seeing that the main project won't do it.... Well its not a priority but will see, shouldn't be that hard to do! Tho

**Comment by rex4539** [comment]
Thanks so much, appreciated!

**Comment by AndromedaCLI** [comment]
No problem, its not perfect though as you will see but thats the best I can do with the time I currently have. It should be live in a few minutes!

**Comment by AndromedaCLI** [comment]
Its live now, have fun :)

**Comment by rex4539** [comment]
Yes, it indeed works and hides the short videos but leaves a placeholder where the short videos would be.

I have a feeling that when for example my subscriptions feed will fill with small videos, then the whole screen will be a blank page :)

Oh well, thanks anyway!
