### ISSUE TITLE
[Bug] Low success-rate of "mark as watched" requests in feed

### ISSUE THREAD

**Issue by good-praxis** [11Tuvork28/invidious#20]
**Describe the bug**
I have enabled invidious to hide videos I've already watched from my feed, but at this point hiding them when I watched them elsewhere, by hitting the 'eye' icon on the top left of the thumbnail, has a flunky success-rate and basically never works on the first try. It usually works better to just open the video in a new tab and close it once it's loaded.

**Steps to Reproduce**
1. Set settings to "hide watched videos"
2. Accumulate a couple days worth of watched videos (probably required, it was working well at the beginning)
3. Manually hide videos on your subscription feed by hitting the associated button
4. Get 400 responses for "bad requests" most of the time

**Screenshots**
![image](https://user-images.githubusercontent.com/22496800/223079779-c37d7248-fc57-4d90-add7-4caeffb2f9a1.png)
The above shows me hiding two specific videos, having gotten rather lucky with a somewhat quick success.

**Additional context**
 - Browser (if applicable): Firefox
 - OS (if applicable): Arch (btw)

**Comment by 11Tuvork28** [comment]
Thanks for bringing this up, seems to be that the cause is `"error": "Invalid signature"`.
Which is caused by the loadbalancer not having  turned sticky sessions, will fix this asap

**Comment by AndromedaCLI** [comment]
Turns out somehow a setting got lost during the transition from non flux to flux managed manifests.
In short it should be fixed now.

**Comment by good-praxis** [comment]
Edit: nevermind, I just got the 500 randomly and thought it may come back to this, it's resolved now

I'm unsure if this is related (I feel like I was using kittyzone after this was fixed) but now I'm getting `500` errors on my account

Trying to login from a private tab got me

```
Title: ` (DB::PoolRetryAttemptsExceeded)`
Date: `2023-03-07T08:32:22Z`
Route: `/login?referer=%2Ffeed%2Fpopular&type=invidious`
Version: `2023.03.06-36f8dbf @ master`

<details>
<summary>Backtrace</summary>
<p>
   
\```
(DB::PoolRetryAttemptsExceeded)
  from lib/db/src/db/result_set.cr:28:5 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:12 in 'query_one?:as'
  from src/invidious/routes/login.cr:322:7 in 'login'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
\```
</p>
</details>
```

**Comment by AndromedaCLI** [comment]
Yeah I'm havin database issues right now, I didn't pay attention to a disk running low on space. I'm sorry for the inconvenience caused.

-------- Original Message --------
