### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by iBicha** [11Tuvork28/invidious#23]
- Open https://watch.thekitty.zone/api/v1/trending?fields=title%2CvideoId%2CvideoThumbnails%2ClengthSeconds%2CviewCount%2Cauthor%2CpublishedText%2CliveNow%2CisUpcoming%2CpremiereTimestamp&region=CA&type=Music

You will see that the thumbnail urls are not valid (e.g. https://watch.thekitty.zonehttps://proxy.invidio.xamh.de/vi/r6WbbU_lLCA/maxres.jpg?host=i.ytimg.com) which looks like the host and proxy appended together

**Comment by AndromedaCLI** [comment]
Oh shit! You're right, will be fixing it ASAP!
