### ISSUE TITLE
[Bug] subscriptions feed doesn't update

### ISSUE THREAD

**Issue by k0zyrev** [11Tuvork28/invidious#3]
https://invidio.xamh.de/

Subscriptions feed only contains older videos. As of now, the newest video was shared 7 hours ago

**Comment by AndromedaCLI** [comment]
Thanks for the heads up! 
Its fixed now, sometimes it hangs up and I need to restart it.

**Comment by k0zyrev** [comment]
> it hangs up and I need to restart it.

I think you need to restart it again. Last time when I was googling this problem, I saw other people solving this issue by simply scheduling regular restarts if the daemon with cron.

**Comment by AndromedaCLI** [comment]
Thanks, I really should do that but I'm in the process of moving my infrastructure so in don't have much time to maintain it at the moment. But after that the instance will run on kubernetes with auto restarts so it should be fixed in a few days. I promise^^
