### ISSUE TITLE
[Feature request] Option to play playlists in reverse order

### ISSUE THREAD

**Issue by k0zyrev** [11Tuvork28/invidious#8]
Often creators do not bother to sort playlists in chronological order and simply add videos as is, puts new videos to the top. Most of the time watching playlists in default order doesn't make any sense and instead of autoplaying it I'd have to manually select the correct video to play next. It would be nice to have a toggle to automatically play previous video in the list instead of the next one.

**Comment by AndromedaCLI** [comment]
Hi, thank you for pointing this out!
I will implement said toggle asap ~2ish days is the ETA.
Other question I have, do you like or use the new playlist features? And if so have you found them useful? 
Would appreciate if you could answer that, as I dont really have any idea how the feature is used/liked.

**Comment by k0zyrev** [comment]
> do you like or use the new playlist features? And if so have you found them useful?

To be honest, haven't had the chance to use it yet. Frankly, what I described above is my number one use-case for playlists. As in I find some channel which covers an interesting topic, look up playlist for that and often times see that it's in reverse order.

 I can tell that keyboard shortcuts are useful without any doubt but that's about it.

**Comment by AndromedaCLI** [comment]
Thats great and all good!
I'm currently working on some optimitzations in the infrastructure, after that I will be working on your request!

**Comment by AndromedaCLI** [comment]
@k0zyrev Sorry that its taking so long, but I nearly finished it I just need to work out some bugs then I will release it.

**Comment by AndromedaCLI** [comment]
Finally got around to it @k0zyrev, should be live in a few minutes ~10-15min
